name: quote_void
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.0.8
  flutter_riverpod: ^2.2.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  uuid: ^3.0.7
  cloud_firestore: ^4.4.3
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AuthIcons
      fonts:
        - asset: assets/fonts/AuthIcons.ttf
